name: ml
channels:
  - robostack
  - conda-forge
  - defaults
dependencies:
  - blas=2.115
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.14.4
  - cudatoolkit=9.0
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - gmp=6.2.1
  - gnutls=3.6.13
  - gobject-introspection=1.66.1
  - graphite2=1.3.13
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - intel-openmp=2022.0.0
  - jasper=1.900.1
  - joblib=1.1.0
  - jpeg=9e
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcroco=0.6.13
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgfortran=5.0.0
  - libgfortran-ng=3.0.1
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libopenblas=0.3.20
  - libopencv=4.5.0
  - libopus=1.3.1
  - libpng=1.6.37
  - librsvg=2.50.2
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.10
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mkl=2022.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.6
  - ninja=1.11.0
  - olefile=0.46
  - openblas=0.3.20
  - opencv=4.5.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - pango=1.42.4
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.1.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.5.0
  - pycparser=2.21
  - python=3.7.6
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytz=2022.1
  - readline=8.1.2
  - setuptools=63.2.0
  - six=1.16.0
  - sqlite=3.39.1
  - tbb=2021.5.0
  - tk=8.6.12
  - wheel=0.37.1
  - x264=1!161.3030
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - albumentations==0.4.3
    - appdirs==1.4.3
    - appnope==0.1.3
    - astor==0.8.1
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bcrypt==3.1.7
    - black==19.10b0
    - bleach==3.1.0
    - boto3==1.10.50
    - botocore==1.13.50
    - cached-property==1.5.1
    - cachetools==4.1.0
    - catboost==0.20.2
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.4.1
    - colorama==0.4.3
    - commonmark==0.9.1
    - cryptography==2.9.2
    - cycler==0.10.0
    - dask==2.17.2
    - decorator==4.4.1
    - defusedxml==0.6.0
    - distributed==2.17.0
    - distro==1.5.0
    - docker==4.2.1
    - docker-compose==1.26.0
    - dockerpty==0.4.1
    - docopt==0.6.2
    - docutils==0.14
    - easydict==1.9
    - efficientnet-pytorch==0.7.1
    - entrypoints==0.3
    - fastparquet==0.3.3
    - filelock==3.0.12
    - flake8==3.7.8
    - flake8-bugbear==19.8.0
    - flask==1.1.1
    - fsspec==0.7.4
    - future==0.18.2
    - gast==0.2.2
    - gitdb2==2.0.5
    - gitpython==3.0.3
    - google-api-core==1.16.0
    - google-api-python-client==1.8.0
    - google-auth==1.13.1
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - googleapis-common-protos==1.51.0
    - grpcio==1.26.0
    - gunicorn==20.0.4
    - h5py==2.10.0
    - heapdict==1.0.1
    - httplib2==0.17.2
    - hyperopt==0.2.4
    - idna==2.8
    - imageio==2.6.1
    - imagesize==1.2.0
    - imgaug==0.2.6
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - iterative-stratification==0.1.6
    - itsdangerous==1.1.0
    - jedi==0.15.2
    - jeepney==0.4.3
    - jinja2==2.10.3
    - jmespath==0.9.4
    - json5==0.8.5
    - jsonpickle==1.4.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.0.0
    - jupyter-core==4.6.1
    - jupyterlab==1.2.4
    - jupyterlab-server==1.0.6
    - kaggle==1.5.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - keyring==21.2.0
    - kiwisolver==1.1.0
    - lightgbm==2.3.1
    - llvmlite==0.31.0
    - locket==0.2.0
    - markdown==2.6.11
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.0.2
    - msgpack==1.0.0
    - munch==2.5.0
    - nbconvert==5.6.1
    - nbformat==5.0.3
    - networkx==2.4
    - nltk==3.4.5
    - notebook==6.0.2
    - numba==0.48.0
    - numpy==1.18.1
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - opencv-python-headless==4.2.0.32
    - opt-einsum==3.1.0
    - packaging==20.3
    - pandas==1.0.4
    - pandocfilters==1.4.2
    - paramiko==2.7.1
    - parso==0.5.2
    - partd==1.1.0
    - pathspec==0.8.0
    - patsy==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pkginfo==1.5.0.1
    - plotly==4.4.1
    - pluggy==0.13.1
    - pretrainedmodels==0.7.4
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - protobuf==3.11.2
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - py==1.8.1
    - py-cpuinfo==5.0.0
    - py-gfm==0.1.4
    - py-rouge==1.1
    - pyaml==20.4.0
    - pyarrow==0.16.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.5.2
    - pynacl==1.4.0
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - pytest==5.3.2
    - python-dotenv==0.13.0
    - python-graphviz==0.20
    - python-slugify==4.0.0
    - pyvips==2.1.12
    - pywavelets==1.1.1
    - pyyaml==5.3
    - pyzmq==18.1.0
    - qtconsole==4.6.0
    - readme-renderer==26.0
    - recommonmark==0.6.0
    - regex==2020.1.8
    - requests==2.22.0
    - requests-mock==1.7.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - rsa==4.0
    - s3transfer==0.2.1
    - sacred==0.8.1
    - sacremoses==0.0.38
    - scikit-image==0.16.2
    - scikit-learn==0.22.1
    - scikit-optimize==0.7.4
    - scipy==1.4.1
    - seaborn==0.10.0
    - secretstorage==3.1.2
    - send2trash==1.5.0
    - sentencepiece==0.1.85
    - sh==1.12.14
    - smmap==3.0.2
    - smmap2==3.0.1
    - snowballstemmer==2.0.0
    - sortedcontainers==2.1.0
    - sphinx==2.2.0
    - sphinx-autodoc-typehints==1.10.3
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - statsmodels==0.11.1
    - subword-nmt==0.3.7
    - tblib==1.6.0
    - tensorboard==2.1.1
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - text-unidecode==1.3
    - texttable==1.6.2
    - thrift==0.13.0
    - tokenizers==0.7.0
    - toml==0.10.0
    - toolz==0.10.0
    - torch==1.12.0
    - torchvision==0.13.0
    - tornado==6.0.3
    - tqdm==4.46.1
    - traitlets==4.3.3
    - transformers==2.11.0
    - tsfresh==0.16.0
    - twine==3.1.1
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.1
    - unidecode==1.1.1
    - uritemplate==3.0.1
    - urllib3==1.24.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - wtfml==0.0.3
    - zict==2.0.0
    - zipp==0.6.0
